App\Entity\Category:
    type: entity
    repositoryClass: App\Repository\CategoryRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 63

    oneToMany:
        jobs:
            targetEntity: Job
            mappedBy: category

    manyToMany:
        affiliates:
            targetEntity: Affiliate
            inversedBy: categories
